(cl:in-package can_ankle-msg)
(cl:export '(TORQUEVALUE-VAL
          TORQUEVALUE
          RETURNTORQUEVALUE-VAL
          RETURNTORQUEVALUE
          VELOCITYVALUE-VAL
          VELOCITYVALUE
          RETURNVELOCITY-VAL
          RETURNVELOCITY
          PDVELOCITY-VAL
          PDVELOCITY
          FORCESENSORTORQUE-VAL
          FORCESENSORTORQUE
))