// Generated by gencpp from file can_ankle/ForceSensor.msg
// DO NOT EDIT!


#ifndef CAN_ANKLE_MESSAGE_FORCESENSOR_H
#define CAN_ANKLE_MESSAGE_FORCESENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_ankle
{
template <class ContainerAllocator>
struct ForceSensor_
{
  typedef ForceSensor_<ContainerAllocator> Type;

  ForceSensor_()
    : ForceValue(0.0)  {
    }
  ForceSensor_(const ContainerAllocator& _alloc)
    : ForceValue(0.0)  {
  (void)_alloc;
    }



   typedef float _ForceValue_type;
  _ForceValue_type ForceValue;





  typedef boost::shared_ptr< ::can_ankle::ForceSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_ankle::ForceSensor_<ContainerAllocator> const> ConstPtr;

}; // struct ForceSensor_

typedef ::can_ankle::ForceSensor_<std::allocator<void> > ForceSensor;

typedef boost::shared_ptr< ::can_ankle::ForceSensor > ForceSensorPtr;
typedef boost::shared_ptr< ::can_ankle::ForceSensor const> ForceSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_ankle::ForceSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_ankle::ForceSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_ankle::ForceSensor_<ContainerAllocator1> & lhs, const ::can_ankle::ForceSensor_<ContainerAllocator2> & rhs)
{
  return lhs.ForceValue == rhs.ForceValue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_ankle::ForceSensor_<ContainerAllocator1> & lhs, const ::can_ankle::ForceSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_ankle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::can_ankle::ForceSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_ankle::ForceSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_ankle::ForceSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_ankle::ForceSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ankle::ForceSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ankle::ForceSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_ankle::ForceSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0610f446d964ed45a89ead06523db642";
  }

  static const char* value(const ::can_ankle::ForceSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0610f446d964ed45ULL;
  static const uint64_t static_value2 = 0xa89ead06523db642ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_ankle::ForceSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_ankle/ForceSensor";
  }

  static const char* value(const ::can_ankle::ForceSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_ankle::ForceSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ForceValue\n"
"\n"
;
  }

  static const char* value(const ::can_ankle::ForceSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_ankle::ForceSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ForceValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_ankle::ForceSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_ankle::ForceSensor_<ContainerAllocator>& v)
  {
    s << indent << "ForceValue: ";
    Printer<float>::stream(s, indent + "  ", v.ForceValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_ANKLE_MESSAGE_FORCESENSOR_H
