// Generated by gencpp from file can_ankle/Torque.msg
// DO NOT EDIT!


#ifndef CAN_ANKLE_MESSAGE_TORQUE_H
#define CAN_ANKLE_MESSAGE_TORQUE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_ankle
{
template <class ContainerAllocator>
struct Torque_
{
  typedef Torque_<ContainerAllocator> Type;

  Torque_()
    : TorqueValue(0.0)
    , ReturnTorqueValue(0.0)
    , VelocityValue(0.0)
    , ReturnVelocity(0.0)
    , PDvelocity(0.0)
    , ForceSensortorque(0.0)  {
    }
  Torque_(const ContainerAllocator& _alloc)
    : TorqueValue(0.0)
    , ReturnTorqueValue(0.0)
    , VelocityValue(0.0)
    , ReturnVelocity(0.0)
    , PDvelocity(0.0)
    , ForceSensortorque(0.0)  {
  (void)_alloc;
    }



   typedef double _TorqueValue_type;
  _TorqueValue_type TorqueValue;

   typedef double _ReturnTorqueValue_type;
  _ReturnTorqueValue_type ReturnTorqueValue;

   typedef double _VelocityValue_type;
  _VelocityValue_type VelocityValue;

   typedef double _ReturnVelocity_type;
  _ReturnVelocity_type ReturnVelocity;

   typedef double _PDvelocity_type;
  _PDvelocity_type PDvelocity;

   typedef float _ForceSensortorque_type;
  _ForceSensortorque_type ForceSensortorque;





  typedef boost::shared_ptr< ::can_ankle::Torque_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_ankle::Torque_<ContainerAllocator> const> ConstPtr;

}; // struct Torque_

typedef ::can_ankle::Torque_<std::allocator<void> > Torque;

typedef boost::shared_ptr< ::can_ankle::Torque > TorquePtr;
typedef boost::shared_ptr< ::can_ankle::Torque const> TorqueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_ankle::Torque_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_ankle::Torque_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::can_ankle::Torque_<ContainerAllocator1> & lhs, const ::can_ankle::Torque_<ContainerAllocator2> & rhs)
{
  return lhs.TorqueValue == rhs.TorqueValue &&
    lhs.ReturnTorqueValue == rhs.ReturnTorqueValue &&
    lhs.VelocityValue == rhs.VelocityValue &&
    lhs.ReturnVelocity == rhs.ReturnVelocity &&
    lhs.PDvelocity == rhs.PDvelocity &&
    lhs.ForceSensortorque == rhs.ForceSensortorque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::can_ankle::Torque_<ContainerAllocator1> & lhs, const ::can_ankle::Torque_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace can_ankle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::can_ankle::Torque_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_ankle::Torque_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_ankle::Torque_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_ankle::Torque_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ankle::Torque_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_ankle::Torque_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_ankle::Torque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1c893b945ede6496888af3eab4a52a8";
  }

  static const char* value(const ::can_ankle::Torque_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1c893b945ede649ULL;
  static const uint64_t static_value2 = 0x6888af3eab4a52a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_ankle::Torque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_ankle/Torque";
  }

  static const char* value(const ::can_ankle::Torque_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_ankle::Torque_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 TorqueValue\n"
"float64 ReturnTorqueValue\n"
"float64 VelocityValue\n"
"float64 ReturnVelocity\n"
"float64 PDvelocity\n"
"float32 ForceSensortorque\n"
"\n"
;
  }

  static const char* value(const ::can_ankle::Torque_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_ankle::Torque_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TorqueValue);
      stream.next(m.ReturnTorqueValue);
      stream.next(m.VelocityValue);
      stream.next(m.ReturnVelocity);
      stream.next(m.PDvelocity);
      stream.next(m.ForceSensortorque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Torque_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_ankle::Torque_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_ankle::Torque_<ContainerAllocator>& v)
  {
    s << indent << "TorqueValue: ";
    Printer<double>::stream(s, indent + "  ", v.TorqueValue);
    s << indent << "ReturnTorqueValue: ";
    Printer<double>::stream(s, indent + "  ", v.ReturnTorqueValue);
    s << indent << "VelocityValue: ";
    Printer<double>::stream(s, indent + "  ", v.VelocityValue);
    s << indent << "ReturnVelocity: ";
    Printer<double>::stream(s, indent + "  ", v.ReturnVelocity);
    s << indent << "PDvelocity: ";
    Printer<double>::stream(s, indent + "  ", v.PDvelocity);
    s << indent << "ForceSensortorque: ";
    Printer<float>::stream(s, indent + "  ", v.ForceSensortorque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_ANKLE_MESSAGE_TORQUE_H
