# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from can_ankle/Torque.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Torque(genpy.Message):
  _md5sum = "f1c893b945ede6496888af3eab4a52a8"
  _type = "can_ankle/Torque"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 TorqueValue
float64 ReturnTorqueValue
float64 VelocityValue
float64 ReturnVelocity
float64 PDvelocity
float32 ForceSensortorque

"""
  __slots__ = ['TorqueValue','ReturnTorqueValue','VelocityValue','ReturnVelocity','PDvelocity','ForceSensortorque']
  _slot_types = ['float64','float64','float64','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TorqueValue,ReturnTorqueValue,VelocityValue,ReturnVelocity,PDvelocity,ForceSensortorque

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Torque, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.TorqueValue is None:
        self.TorqueValue = 0.
      if self.ReturnTorqueValue is None:
        self.ReturnTorqueValue = 0.
      if self.VelocityValue is None:
        self.VelocityValue = 0.
      if self.ReturnVelocity is None:
        self.ReturnVelocity = 0.
      if self.PDvelocity is None:
        self.PDvelocity = 0.
      if self.ForceSensortorque is None:
        self.ForceSensortorque = 0.
    else:
      self.TorqueValue = 0.
      self.ReturnTorqueValue = 0.
      self.VelocityValue = 0.
      self.ReturnVelocity = 0.
      self.PDvelocity = 0.
      self.ForceSensortorque = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5df().pack(_x.TorqueValue, _x.ReturnTorqueValue, _x.VelocityValue, _x.ReturnVelocity, _x.PDvelocity, _x.ForceSensortorque))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.TorqueValue, _x.ReturnTorqueValue, _x.VelocityValue, _x.ReturnVelocity, _x.PDvelocity, _x.ForceSensortorque,) = _get_struct_5df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5df().pack(_x.TorqueValue, _x.ReturnTorqueValue, _x.VelocityValue, _x.ReturnVelocity, _x.PDvelocity, _x.ForceSensortorque))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.TorqueValue, _x.ReturnTorqueValue, _x.VelocityValue, _x.ReturnVelocity, _x.PDvelocity, _x.ForceSensortorque,) = _get_struct_5df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5df = None
def _get_struct_5df():
    global _struct_5df
    if _struct_5df is None:
        _struct_5df = struct.Struct("<5df")
    return _struct_5df
